[general]
batch_size = 1
caption_extension = ""

[[datasets]]
image_directory = "E:/lora_training/Data/input/ymir/1_ymir"
caption_extension = ".txt"
num_repeats = 1
cache_directory = "E:/lora_training/Data/input/ymir/1_ymir"

  [[datasets.subsets]]
  resolution = 1024
  enable_bucket = true
  min_bucket_reso = 256
  max_bucket_reso = 1280
  bucket_no_upscale = true
  shuffle_caption = false
  keep_tokens = 0
  flip_aug = false
